// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AuditoryPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void auditoryPage() {
    // Test name: Auditory Page
    // Step # | name | target | value | comment
    // 1 | open | https://us2.admin.mailchimp.com/lists/members?id=971650 |  | 
    driver.get("https://us2.admin.mailchimp.com/lists/members?id=971650");
    // 2 | selectFrame | index=1 |  | 
    driver.switchTo().frame(1);
    // 3 | click | xpath=//td[5] |  | 
    driver.findElement(By.xpath("//td[5]")).click();
    // 4 | click | xpath=//td[5] |  | 
    driver.findElement(By.xpath("//td[5]")).click();
    // 5 | assertText | xpath=//tr[2]/td[5] | 89217777777 | 
    assertThat(driver.findElement(By.xpath("//tr[2]/td[5]")).getText(), is("89217777777"));
    // 6 | click | xpath=//td[7] |  | 
    driver.findElement(By.xpath("//td[7]")).click();
    // 7 | click | xpath=//td[7] |  | 
    driver.findElement(By.xpath("//td[7]")).click();
    // 8 | click | xpath=//td[5] |  | 
    driver.findElement(By.xpath("//td[5]")).click();
    // 9 | click | xpath=//td[4] |  | 
    driver.findElement(By.xpath("//td[4]")).click();
    // 10 | assertText | xpath=//tr[2]/td[4] | Afanasiev | 
    assertThat(driver.findElement(By.xpath("//tr[2]/td[4]")).getText(), is("Afanasiev"));
    // 11 | assertText | xpath=//td[7]/span | Staff | 
    assertThat(driver.findElement(By.xpath("//td[7]/span")).getText(), is("Staff"));
    // 12 | assertText | xpath=//li[6]/span | VIP | 
    assertThat(driver.findElement(By.xpath("//li[6]/span")).getText(), is("VIP"));
    // 13 | assertText | xpath=//tr[4]/td[9] | Admin Add | 
    assertThat(driver.findElement(By.xpath("//tr[4]/td[9]")).getText(), is("Admin Add"));
  }
}
