// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ComplexCalculateMyPriceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void complexCalculateMyPrice() {
    driver.get("https://mailchimp.com//");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.xpath("//a[contains(text(),\'Pick A Plan\')]")).click();
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("(//input[@value=\'0\'])[2]")).sendKeys("11");
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div[2]/div/div[2]/div/div[2]")).getText(), is("540"));
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("(//input[@value=\'0\'])[2]")).sendKeys("8");
    driver.findElement(By.xpath("(//input[@value=\'0\'])[2]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[2]/div/div[3]/div[2]/div/div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//div[2]/div/div[3]/div[2]/div")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div/strong")).getText(), is("40k"));
    driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div[2]/div/div[2]/div/div[2]")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div[2]/div/div[2]/div/div[2]")).getText(), is("290"));
    driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div/div/h2")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div/div/h2")).getText(), is("Standard"));
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("(//input[@value=\'0\'])[2]")).sendKeys("3");
    driver.findElement(By.xpath("(//input[@value=\'0\'])[2]")).click();
    driver.findElement(By.xpath("//div[2]/div/div[3]/div[2]/div")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div/strong")).getText(), is("10k"));
    driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div[2]/div/div[2]/div/div[2]")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[3]/div[2]/div/div[2]/div/div[2]")).getText(), is("105"));
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("//div[3]/div[2]/input")).sendKeys("0");
    driver.findElement(By.xpath("(//input[@value=\'0\'])[2]")).click();
    driver.findElement(By.xpath("(//button[@type=\'button\'])[2]")).click();
    driver.findElement(By.xpath("//div[3]/div[2]/div[2]/div/div/h2")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[2]/div/div/h2")).getText(), is("Premium"));
    driver.findElement(By.xpath("//div[3]/div[2]/div[2]/div[2]/div")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[2]/div[2]/div/div[2]/div/div[2]")).getText(), is("299"));
    driver.findElement(By.xpath("//div/div/button[3]")).click();
    driver.findElement(By.xpath("//div[3]/div[2]/div[4]/div/div/h2")).click();
    assertThat(driver.findElement(By.xpath("//div[3]/div[2]/div[4]/div/div/h2")).getText(), is("Essentials"));
    driver.findElement(By.xpath("//div[4]/p[2]")).click();
    assertThat(driver.findElement(By.xpath("//div[4]/p[2]")).getText(), is("Plan pricing starts at up to 500 contacts. Select your list size to calculate your price. The monthly email send limit is 10 times your maximum contact count."));
    {
      WebElement element = driver.findElement(By.xpath("(//input[@value=\'0\'])[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[4]/div[2]/input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[4]/div[2]/input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("//div[4]/div[2]/input")).sendKeys("10");
    driver.findElement(By.xpath("//div[4]/div[2]/input")).click();
    driver.findElement(By.xpath("//div[2]/div/div[4]/div[2]/div")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[4]/div[2]/div/strong"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[5]/p"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//div[5]/p/a")).getText(), is("You’ll need our Standard plan"));
    driver.close();
  }
}
