// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MailTemplateTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mailTemplate() {
    driver.get("https://us2.admin.mailchimp.com/templates/");
    driver.switchTo().frame(1);
    driver.findElement(By.xpath("//a[contains(text(),\'Create Template\')]")).click();
    driver.switchTo().defaultContent();
    {
      WebElement element = driver.findElement(By.xpath("//a[contains(.,\'Selected Sell Products\')]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//a[contains(.,\'Selected Sell Products\')]")).click();
    driver.findElement(By.xpath("//a[contains(.,\'Save and Exit\')]")).click();
    driver.findElement(By.xpath("//input[2]")).click();
    driver.findElement(By.xpath("//input[2]")).sendKeys("Test");
    driver.findElement(By.xpath("//div[6]/div[2]/div/div/span/span/span/span[3]")).click();
    driver.switchTo().frame(1);
    assertThat(driver.findElement(By.xpath("//a[contains(.,\'Test\')]")).getText(), is("Test"));
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//button/span[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//button/span[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[2]/div/input")).click();
    driver.findElement(By.xpath("//div[2]/div/input")).sendKeys("DELETE");
    driver.findElement(By.xpath("//form/div/div[2]/span/span/span/span[3]")).click();
    assertThat(driver.findElement(By.cssSelector(".c-noDataBlock_title")).getText(), is("You don\\\'t have any saved templates"));
    driver.close();
  }
}
