// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SupportPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void supportPage() {
    driver.get("https://mailchimp.com/help/");
    driver.findElement(By.xpath("//header/h2")).click();
    assertThat(driver.findElement(By.xpath("//header/h2")).getText(), is("Popular guides and tutorials"));
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Español']")).click();
    }
    driver.findElement(By.xpath("//select")).click();
    driver.findElement(By.xpath("//header/h2")).click();
    assertThat(driver.findElement(By.xpath("//header/h2")).getText(), is("Guías y tutoriales populares"));
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Français']")).click();
    }
    driver.findElement(By.xpath("//select")).click();
    driver.findElement(By.xpath("//header/h2")).click();
    assertThat(driver.findElement(By.xpath("//header/h2")).getText(), is("Guides et tutoriels populaires"));
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Português - Brasil']")).click();
    }
    driver.findElement(By.xpath("//select")).click();
    driver.findElement(By.xpath("//header/h2")).click();
    assertThat(driver.findElement(By.xpath("//header/h2")).getText(), is("Guias e tutoriais populares"));
    driver.findElement(By.xpath("//main")).click();
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Deutsch']")).click();
    }
    driver.findElement(By.xpath("//select")).click();
    driver.findElement(By.xpath("//header/h2")).click();
    assertThat(driver.findElement(By.xpath("//header/h2")).getText(), is("Beliebte Leitfäden und Tutorials"));
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'English']")).click();
    }
    driver.findElement(By.xpath("//select")).click();
    driver.findElement(By.xpath("//div[2]/div/form/input")).click();
    driver.findElement(By.xpath("//div[2]/div/form/input")).sendKeys("import contacts");
    driver.findElement(By.xpath("(//button[@type=\'submit\'])[3]")).click();
    driver.findElement(By.xpath("//main/div/div[2]")).click();
    assertThat(driver.findElement(By.xpath("//em[2]")).getText(), is("Contacts"));
    driver.findElement(By.xpath("//input[@id=\'q\']")).sendKeys("Use the Cookie Banner on Your Website");
    driver.findElement(By.xpath("(//button[@type=\'submit\'])[3]")).click();
    driver.findElement(By.xpath("//main/div/div[2]")).click();
    assertThat(driver.findElement(By.xpath("//div/h2/a")).getText(), is("Use the Cookie Banner on Your Website"));
    driver.close();
  }
}
