// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UpdateSelfInfoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void updateSelfInfo() {
    driver.get("https://us2.admin.mailchimp.com/account/profile/");
    driver.switchTo().frame(1);
    driver.switchTo().frame(0);
    driver.switchTo().defaultContent();
    assertThat(driver.findElement(By.xpath("//div[2]/fieldset/h3")).getText(), is("Change password"));
    assertFalse(driver.findElement(By.xpath("//label[2]/div/input")).isSelected());
    driver.findElement(By.xpath("//label[2]/div/input")).click();
    driver.findElement(By.xpath("//span[@id=\'dijit_form_Button_1\']/span[3]")).click();
    assertTrue(driver.findElement(By.xpath("//main[@id=\'content\']/div[5]/div/form/table/tbody/tr/td[3]/div/label[2]/div/input")).isSelected());
    driver.findElement(By.xpath("//main[@id=\'content\']/div[5]/div/form/table/tbody/tr/td[3]/div/label[2]/div/input")).click();
    driver.findElement(By.xpath("//span[@id=\'dijit_form_Button_1\']/span[3]")).click();
    assertFalse(driver.findElement(By.xpath("//input[@id=\'notify_0_email\']")).isSelected());
  }
}
